# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:

    docker:
      - image: cimg/node:20.17

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm ci

      # Run linters and tests
      - run:
          name: Run Linters and Unit Tests
          command: |
            npm run build
            npm run lint
            npm run coverage
